# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255)),
                ('uid', models.CharField(editable=False, max_length=500, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('u', 'User'), ('m', 'Manager'), ('a', 'Administrator')], default='u', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
